repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: check-symlinks
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.27.0
    hooks:
      - id: yapf
