repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: name-tests-test
      - id: check-symlinks
